import test from 'node:test';import assert from 'node:assert/strict';
const signal=()=>({listeners:[],addListener(f){this.listeners.push(f);},emit(...a){this.listeners.forEach(f=>f(...a));}});
test('worker wires permitted frame discovery, selection, native start and confirmed exact local pause',async()=>{
 const {createWorker}=await import('../../extension/worker.mjs');const calls=[];
 const request=Object.assign(signal(),{removeListener(){},filters:[]});
 const chrome={runtime:{id:'ext',getURL:p=>`chrome-extension://ext/${p}`,onMessage:signal()},tabs:{onRemoved:signal(),sendMessage:async(...a)=>{calls.push(a);return {ok:true};}},webNavigation:{onCommitted:signal(),onHistoryStateUpdated:signal(),getAllFrames:async()=>[{frameId:0,documentId:'a'},{frameId:4,documentId:'b'}]},webRequest:{onBeforeRequest:request,onResponseStarted:Object.assign(signal(),{removeListener(){}})},permissions:{getAll:async()=>({origins:['http://*/*','https://*/*']}),onAdded:signal(),onRemoved:signal()},scripting:{executeScript:async o=>{calls.push(o);if(o.target.documentIds[0]==='b')throw Error('denied');}},alarms:{create(){},onAlarm:signal()}};
 const native={view:()=>({state:'playing',evidence:'unverified',capabilities:['start'],receivers:[{identifier:'r',address:'192.168.1.9',label:'TV'}]}),request:async(op,args)=>{calls.push({op,args});return native.view();}};
 const w=createWorker(chrome,native);const send=m=>w.message({...m,tabId:1},{url:'chrome-extension://ext/popup.html'});
 assert.equal((await send({op:'enable'})).scanned,1);
 await w.message({op:'videos',videos:[{videoId:'v1',url:'https://x/movie?sig=%2f'}]},{tab:{id:1},frameId:0,documentId:'a'});
 const state=await send({op:'view'});assert.equal(state.candidates.length,1);
 await assert.rejects(send({op:'start'}));await send({op:'select',id:state.candidates[0].id});await send({op:'receiver',id:'r'});await send({op:'start'});
 assert.equal(calls.at(-1).args.url,'https://x/movie?sig=%2f');assert.equal(calls.some(c=>Array.isArray(c)&&c[1]?.op==='localPause'),false);
 await assert.rejects(send({op:'localPause'}));await send({op:'localPause',confirmed:true});assert.equal(calls.at(-1)[2].documentId,'a');
 await send({op:'localResume'});assert.equal(calls.at(-1)[1].op,'localResume');
 await assert.rejects(w.message({op:'stop'},{tab:{id:1},url:'https://evil/'}));
 chrome.webNavigation.onCommitted.emit({tabId:1,frameId:0,documentId:'new'});assert.equal((await send({op:'view'})).candidates.length,0);
 await w.message({op:'videos',videos:[{videoId:'v1',url:'https://x/old'}]},{tab:{id:1},frameId:0,documentId:'a'});assert.equal((await send({op:'view'})).candidates.length,0);
 chrome.webNavigation.onHistoryStateUpdated.emit({tabId:1,frameId:0,documentId:'a'});await send({op:'rescan'});
 await w.message({op:'videos',videos:[{videoId:'v2',url:'https://x/child'}]},{tab:{id:1},frameId:4,documentId:'b'});assert.equal((await send({op:'view'})).candidates.length,1);
 chrome.webNavigation.getAllFrames=async()=>{chrome.webNavigation.onCommitted.emit({tabId:1,frameId:0,documentId:'raced'});return [{frameId:4,documentId:'b'}];};
 await send({op:'rescan'});await w.message({op:'videos',videos:[{videoId:'v2',url:'https://x/stale'}]},{tab:{id:1},frameId:4,documentId:'b'});assert.equal((await send({op:'view'})).candidates.length,0);
});
test('webRequest is attached only after optional host permission and detached on revoke',async()=>{
 const {createWorker}=await import('../../extension/worker.mjs');
 const before={listeners:[],filters:[],addListener(f,filter){this.listeners.push(f);this.filters.push(filter);},removeListener(f){this.listeners=this.listeners.filter(x=>x!==f);this.filters=[];}};
 const started={listeners:[],filters:[],addListener(f,filter,extra){this.listeners.push(f);this.filters.push(filter);this.extra=extra;},removeListener(f){this.listeners=this.listeners.filter(x=>x!==f);this.filters=[];}};
 let origins=[];
 const chrome={runtime:{id:'ext',getURL:p=>`chrome-extension://ext/${p}`,onMessage:signal()},tabs:{onRemoved:signal()},webNavigation:{onCommitted:signal(),onHistoryStateUpdated:signal(),getAllFrames:async()=>[]},webRequest:{onBeforeRequest:before,onResponseStarted:started},permissions:{getAll:async()=>({origins:[...origins]}),onAdded:signal(),onRemoved:signal()},scripting:{executeScript:async()=>{}},alarms:{create(){},onAlarm:signal()}};
 createWorker(chrome);await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,0);assert.equal(started.listeners.length,0);
 origins=['http://site.test/*'];chrome.permissions.onAdded.emit({origins});await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,1);assert.deepEqual(before.filters[0],{urls:['http://site.test/*']});
 origins=['http://*/*','https://*/*'];chrome.permissions.onAdded.emit({origins});await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,1);assert.deepEqual(before.filters[0],{urls:['http://*/*','https://*/*']});
 assert.deepEqual(started.extra,['responseHeaders']);
 origins=[];chrome.permissions.onRemoved.emit({origins:['http://*/*','https://*/*']});await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,0);assert.equal(started.listeners.length,0);
});
