import test from 'node:test';import assert from 'node:assert/strict';
const signal=()=>({listeners:[],addListener(f){this.listeners.push(f);},emit(...a){this.listeners.forEach(f=>f(...a));}});
test('worker wires permitted frame discovery, selection, native start and confirmed exact local pause',async()=>{
 const {createWorker}=await import('../../extension/worker.mjs');const calls=[];
 const request=Object.assign(signal(),{removeListener(){},filters:[]});
 const chrome={runtime:{id:'ext',getURL:p=>`chrome-extension://ext/${p}`,onMessage:signal(),onInstalled:signal()},tabs:{create:async options=>{calls.push({created:options});},onRemoved:signal(),sendMessage:async(...a)=>{calls.push(a);return {ok:true};}},webNavigation:{onCommitted:signal(),onHistoryStateUpdated:signal(),getAllFrames:async()=>[{frameId:0,documentId:'a'},{frameId:4,documentId:'b'}]},webRequest:{onBeforeRequest:request,onResponseStarted:Object.assign(signal(),{removeListener(){}})},permissions:{getAll:async()=>({origins:['http://*/*','https://*/*']}),onAdded:signal(),onRemoved:signal()},scripting:{executeScript:async o=>{calls.push(o);if(o.target.documentIds[0]==='b')throw Error('denied');}},alarms:{create(){},onAlarm:signal()}};
 const native={view:()=>({state:'playing',evidence:'unverified',capabilities:['start'],receivers:[{identifier:'r',address:'192.168.1.9',label:'TV'}]}),request:async(op,args)=>{calls.push({op,args});return native.view();}};
 const w=createWorker(chrome,native);const send=m=>w.message({...m,tabId:1},{url:'chrome-extension://ext/popup.html'});
 chrome.runtime.onInstalled.emit({reason:'install'});await new Promise(r=>setImmediate(r));
 assert.deepEqual(calls.filter(c=>c.created),[{created:{url:'chrome-extension://ext/setup.html'}}]);
 chrome.runtime.onInstalled.emit({reason:'update'});await new Promise(r=>setImmediate(r));
 assert.equal(calls.filter(c=>c.created).length,1);
 const setupSender={url:'chrome-extension://ext/setup.html',tab:{id:2},frameId:0};
 await w.message({op:'setupCheck'},setupSender);
 assert.equal(calls.at(-1).op,'hello');
 await assert.rejects(w.message({op:'start'},setupSender));
 await assert.rejects(w.message({op:'setupCheck'},{...setupSender,frameId:1}));
 await assert.rejects(w.message({op:'setupCheck'},{url:'https://evil/',tab:{id:2}}));
 assert.equal((await send({op:'enable'})).scanned,1);
 await w.message({op:'videos',videos:[{videoId:'v1',url:'https://x/movie?sig=%2f'}]},{tab:{id:1},frameId:0,documentId:'a'});
 const state=await send({op:'view'});assert.equal(state.candidates.length,1);
 await assert.rejects(send({op:'start'}));await send({op:'select',id:state.candidates[0].id});await send({op:'receiver',id:'r'});await send({op:'start'});
 assert.equal(calls.at(-1).args.url,'https://x/movie?sig=%2f');assert.equal(calls.some(c=>Array.isArray(c)&&c[1]?.op==='localPause'),false);
 await assert.rejects(send({op:'localPause'}));await send({op:'localPause',confirmed:true});assert.equal(calls.at(-1)[2].documentId,'a');
 await send({op:'localResume'});assert.equal(calls.at(-1)[1].op,'localResume');
 await send({op:'discover'});
 assert.equal((await send({op:'view'})).receiver,'r');
 await assert.rejects(w.message({op:'stop'},{tab:{id:1},url:'https://evil/'}));
 chrome.webNavigation.onCommitted.emit({tabId:1,frameId:0,documentId:'new'});assert.equal((await send({op:'view'})).candidates.length,0);
 await w.message({op:'videos',videos:[{videoId:'v1',url:'https://x/old'}]},{tab:{id:1},frameId:0,documentId:'a'});assert.equal((await send({op:'view'})).candidates.length,0);
 chrome.webNavigation.onHistoryStateUpdated.emit({tabId:1,frameId:0,documentId:'a'});await send({op:'rescan'});
 await w.message({op:'videos',videos:[{videoId:'v2',url:'https://x/child'}]},{tab:{id:1},frameId:4,documentId:'b'});assert.equal((await send({op:'view'})).candidates.length,1);
 chrome.webNavigation.getAllFrames=async()=>{chrome.webNavigation.onCommitted.emit({tabId:1,frameId:0,documentId:'raced'});return [{frameId:4,documentId:'b'}];};
 await send({op:'rescan'});await w.message({op:'videos',videos:[{videoId:'v2',url:'https://x/stale'}]},{tab:{id:1},frameId:4,documentId:'b'});assert.equal((await send({op:'view'})).candidates.length,0);
});
test('firewall changes require popup confirmation for the selected receiver; checks never mutate',async()=>{
 const {createWorker}=await import('../../extension/worker.mjs');const calls=[];
 const chrome={runtime:{getURL:p=>`chrome-extension://ext/${p}`,onMessage:signal()},tabs:{onRemoved:signal()},webNavigation:{onCommitted:signal(),onHistoryStateUpdated:signal()},webRequest:{onBeforeRequest:{removeListener(){}},onResponseStarted:{removeListener(){}}},permissions:{getAll:async()=>({origins:[]}),onAdded:signal(),onRemoved:signal()},alarms:{create(){},onAlarm:signal()}};
 let support=true;
 const native={view:()=>({firewallSupport:support,receivers:[{identifier:'r',address:'192.168.1.50'}]}),request:async(op,args)=>{calls.push({op,args});return {supported:true,enabled:true,allowance:'missing',owned:false,...(args.action==='allow'?{change:{ok:false,error:'auth_cancelled'}}:{})}}};
 const w=createWorker(chrome,native);const popup={url:chrome.runtime.getURL('popup.html')};
 const send=m=>w.message(m,popup);
 await send({op:'receiver',id:'r'});
 assert.deepEqual(calls,[{op:'firewall',args:{receiver:'r',host:'192.168.1.50',action:'check'}}]);
 await assert.rejects(send({op:'firewall',action:'allow',receiver:'r'}));
 await assert.rejects(send({op:'firewall',action:'allow',receiver:'stale',confirmed:true}));
 await assert.rejects(w.message({op:'firewall',action:'allow',receiver:'r',confirmed:true},{url:'https://evil/',tab:{id:1}}));
 assert.equal(calls.length,1);
 await send({op:'firewall',action:'allow',receiver:'r',confirmed:true});
 assert.equal(calls.at(-1).args.action,'allow');
 assert.equal((await send({op:'view'})).firewall.host,'192.168.1.50');
 await send({op:'discover'});
 assert.equal((await send({op:'view'})).firewall.change.error,'auth_cancelled');
 support=false;await send({op:'receiver',id:'r'});
 assert.equal((await send({op:'view'})).firewall,null);
});
test('webRequest is attached only after optional host permission and detached on revoke',async()=>{
 const {createWorker}=await import('../../extension/worker.mjs');
 const before={listeners:[],filters:[],addListener(f,filter){this.listeners.push(f);this.filters.push(filter);},removeListener(f){this.listeners=this.listeners.filter(x=>x!==f);this.filters=[];}};
 const started={listeners:[],filters:[],addListener(f,filter,extra){this.listeners.push(f);this.filters.push(filter);this.extra=extra;},removeListener(f){this.listeners=this.listeners.filter(x=>x!==f);this.filters=[];}};
 let origins=[];
 const chrome={runtime:{id:'ext',getURL:p=>`chrome-extension://ext/${p}`,onMessage:signal()},tabs:{onRemoved:signal()},webNavigation:{onCommitted:signal(),onHistoryStateUpdated:signal(),getAllFrames:async()=>[]},webRequest:{onBeforeRequest:before,onResponseStarted:started},permissions:{getAll:async()=>({origins:[...origins]}),onAdded:signal(),onRemoved:signal()},scripting:{executeScript:async()=>{}},alarms:{create(){},onAlarm:signal()}};
 createWorker(chrome);await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,0);assert.equal(started.listeners.length,0);
 origins=['http://site.test/*'];chrome.permissions.onAdded.emit({origins});await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,1);assert.deepEqual(before.filters[0],{urls:['http://site.test/*']});
 origins=['http://*/*','https://*/*'];chrome.permissions.onAdded.emit({origins});await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,1);assert.deepEqual(before.filters[0],{urls:['http://*/*','https://*/*']});
 assert.deepEqual(started.extra,['responseHeaders']);
 origins=[];chrome.permissions.onRemoved.emit({origins:['http://*/*','https://*/*']});await new Promise(r=>setImmediate(r));
 assert.equal(before.listeners.length,0);assert.equal(started.listeners.length,0);
});
test('onMessage replies preserve known static native error codes and collapse unknown secret errors to ACTION_FAILED',async()=>{
 const {createWorker}=await import('../../extension/worker.mjs');
 const request=Object.assign(signal(),{removeListener(){}});
 const chrome={runtime:{id:'ext',getURL:p=>`chrome-extension://ext/${p}`,onMessage:signal(),onInstalled:signal()},tabs:{onRemoved:signal(),sendMessage:async()=>({ok:true})},webNavigation:{onCommitted:signal(),onHistoryStateUpdated:signal(),getAllFrames:async()=>[{frameId:0,documentId:'a'}]},webRequest:{onBeforeRequest:request,onResponseStarted:Object.assign(signal(),{removeListener(){}})},permissions:{getAll:async()=>({origins:['http://*/*','https://*/*']}),onAdded:signal(),onRemoved:signal()},scripting:{executeScript:async()=>{}},alarms:{create(){},onAlarm:signal()}};
 const errorFor={start:'receiver_unavailable',pair:'pairing_failed',status:'connect 192.168.1.9 failed: token=SECRET123'};
 const native={view:()=>({state:'idle',evidence:'none',capabilities:['start','pair','status'],receivers:[{identifier:'r',address:'192.168.1.9'}]}),request:async op=>{if(errorFor[op])throw Error(errorFor[op]);return native.view();}};
 createWorker(chrome,native);
 const handler=chrome.runtime.onMessage.listeners[0];
 const popup={url:chrome.runtime.getURL('popup.html')};
 const call=(m,sender=popup)=>new Promise(resolve=>handler(m,sender,resolve));
 await call({op:'enable',tabId:1});
 await call({op:'videos',videos:[{videoId:'v1',url:'https://x/movie'}]},{tab:{id:1},frameId:0,documentId:'a'});
 const view=await call({op:'view',tabId:1});
 await call({op:'select',tabId:1,id:view.candidates[0].id});
 await call({op:'receiver',id:'r'});
 assert.deepEqual(await call({op:'start',tabId:1}),{ok:false,error:'receiver_unavailable'});
 assert.deepEqual(await call({op:'pair',tabId:1,pin:'1234'}),{ok:false,error:'pairing_failed'});
 assert.deepEqual(await call({op:'status',tabId:1}),{ok:false,error:'ACTION_FAILED'});
});
